### ISSUE TITLE
Create domain entities

### ISSUE THREAD

**Issue by sulton-max** [WoW-2-0-Projects/StudyMate#8]
### Description

Add domain entities

### Requirements

- project must be runnable
- entities must be abstract

### Deliverables and requirements

- `IEntity`
- `ISoftDeletedEntity`
- `IAuditableEntity`
- `ICreationAuditableEntity`
- `IDelationAuditableEntity`
- `IModificationAuditableEntity`

**Comment by samadovxusan** [comment]
Closed
